import { FederalSubjects } from "./subject.schema";

export const FEDERAL_SUBJECTS_CODES_AND_TZ: FederalSubjects  =
    [
        {name: "Республика Адыгея", code: "01", timezone: "UTC+3"},
        {name: "Республика Башкортостан", code: "02", timezone: "UTC+5"},
        {name: "Республика Бурятия", code: "03", timezone: "UTC+8"},
        {name: "Республика Алтай", code: "04", timezone: "UTC+6"},
        {name: "Республика Дагестан", code: "05", timezone: "UTC+3"},
        {name: "Республика Ингушетия", code: "06", timezone: "UTC+3"},
        {name: "Республика Кабардино-Балкария", code: "07", timezone: "UTC+3"},
        {name: "Республика Калмыкия", code: "08", timezone: "UTC+3"},
        {name: "Республика Карачаево-Черкессия", code: "09", timezone: "UTC+3"},
        {name: "Республика Карелия", code: "10", timezone: "UTC+3"},
        {name: "Республика Коми", code: "11", timezone: "UTC+3"},
        {name: "Республика Марий Эл", code: "12", timezone: "UTC+3"},
        {name: "Республика Мордовия", code: "13", timezone: "UTC+3"},
        {name: "Республика Саха (Якутия)", code: "14", timezone: "UTC+11"},
        {name: "Республика Северная Осетия (Алания)", code: "15", timezone: "UTC+3"},
        {name: "Республика Татарстан", code: "16", timezone: "UTC+3"},
        {name: "Республика Тыва (Тува)", code: "17", timezone: "UTC+7"},
        {name: "Республика Удмуртия", code: "18", timezone: "UTC+4"},
        {name: "Республика Хакасия", code: "19", timezone: "UTC+7"},
        {name: "Республика Чечня", code: "20", timezone: "UTC+3"},
        {name: "Республика Чувашия", code: "21", timezone: "UTC+3"},
        {name: "Алтайский край", code: "22", timezone: "UTC+6"},
        {name: "Краснодарский край", code: "23", timezone: "UTC+3"},
        {name: "Красноярский край", code: "24", timezone: "UTC+7"},
        {name: "Приморский край", code: "25", timezone: "UTC+10"},
        {name: "Ставропольский край", code: "26", timezone: "UTC+3"},
        {name: "Хабаровский край", code: "27", timezone: "UTC+10"},
        {name: "Амурская область", code: "28", timezone: "UTC+9"},
        {name: "Архангельская область", code: "29", timezone: "UTC+3"},
        {name: "Астраханская область", code: "30", timezone: "UTC+3"},
        {name: "Белгородская область", code: "31", timezone: "UTC+3"},
        {name: "Брянская область", code: "32", timezone: "UTC+3"},
        {name: "Владимирская область", code: "33", timezone: "UTC+3"},
        {name: "Волгоградская область", code: "34", timezone: "UTC+3"},
        {name: "Вологодская область", code: "35", timezone: "UTC+3"},
        {name: "Воронежская область", code: "36", timezone: "UTC+3"},
        {name: "Ивановская область", code: "37", timezone: "UTC+3"},
        {name: "Иркутская область", code: "38", timezone: "UTC+8"},
        {name: "Калининградская область", code: "39", timezone: "UTC+2"},
        {name: "Калужская область", code: "40", timezone: "UTC+3"},
        {name: "Камчатский край", code: "41", timezone: "UTC+12"},
        {name: "Кемеровская область", code: "42", timezone: "UTC+7"},
        {name: "Кировская область", code: "43", timezone: "UTC+3"},
        {name: "Костромская область", code: "44", timezone: "UTC+3"},
        {name: "Курганская область", code: "45", timezone: "UTC+5"},
        {name: "Курская область", code: "46", timezone: "UTC+3"},
        {name: "Ленинградская область", code: "47", timezone: "UTC+3"},
        {name: "Липецкая область", code: "48", timezone: "UTC+3"},
        {name: "Магаданская область", code: "49", timezone: "UTC+10"},
        {name: "Московская область", code: "50", timezone: "UTC+3"},
        {name: "Мурманская область", code: "51", timezone: "UTC+3"},
        {name: "Нижегородская область", code: "52", timezone: "UTC+3"},
        {name: "Новгородская область", code: "53", timezone: "UTC+3"},
        {name: "Новосибирская область", code: "54", timezone: "UTC+6"},
        {name: "Омская область", code: "55", timezone: "UTC+6"},
        {name: "Оренбургская область", code: "56", timezone: "UTC+5"},
        {name: "Орловская область", code: "57", timezone: "UTC+3"},
        {name: "Пензенская область", code: "58", timezone: "UTC+3"},
        {name: "Пермский край", code: "59", timezone: "UTC+5"},
        {name: "Псковская область", code: "60", timezone: "UTC+3"},
        {name: "Ростовская область", code: "61", timezone: "UTC+3"},
        {name: "Рязанская область", code: "62", timezone: "UTC+3"},
        {name: "Самарская область", code: "63", timezone: "UTC+4"},
        {name: "Саратовская область", code: "64", timezone: "UTC+3"},
        {name: "Сахалинская область", code: "65", timezone: "UTC+11"},
        {name: "Свердловская область", code: "66", timezone: "UTC+5"},
        {name: "Смоленская область", code: "67", timezone: "UTC+3"},
        {name: "Тамбовская область", code: "68", timezone: "UTC+3"},
        {name: "Тверская область", code: "69", timezone: "UTC+3"},
        {name: "Томская область", code: "70", timezone: "UTC+6"},
        {name: "Тульская область", code: "71", timezone: "UTC+3"},
        {name: "Тюменская область", code: "72", timezone: "UTC+5"},
        {name: "Ульяновская область", code: "73", timezone: "UTC+3"},
        {name: "Челябинская область", code: "74", timezone: "UTC+5"},
        {name: "Забайкальский край", code: "75", timezone: "UTC+8"},
        {name: "Ярославская область", code: "76", timezone: "UTC+3"},
        {name: "Москва", code: "77", timezone: "UTC+3"},
        {name: "Санкт-Петербург", code: "78", timezone: "UTC+3"},
        {name: "Еврейская автономная область", code: "79", timezone: "UTC+10"},
        {name: "Ненецкий автономный округ", code: "83", timezone: "UTC+3"},
        {name: "Ханты-Мансийский автономный округ", code: "86", timezone: "UTC+5"},
        {name: "Чукотский автономный округ", code: "87", timezone: "UTC+12"},
        {name: "Ямало-Ненецкий автономный округ", code: "89", timezone: "UTC+5"},
        {name: "Республика Крым", code: "91", timezone: "UTC+3"},
        {name: "Севастополь", code: "92", timezone: "UTC+3"},
        {name: "Иные территории, включая город и космодром Байконур", code: "99", timezone: "UTC+0"}
    ]